News_Portal/News_Portal/News_Portal/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('news/', include('news.urls'))
    #path('search/', include('news.urls'))
]

News_Portal/News_Portal/news/urls.py
from django.urls import path
from .views import NewsListView, NewsDetailView, search_posts, PostCreate

app_name = 'news'

urlpatterns = [
    path('', NewsListView.as_view(), name='news_list'), # Общий список новостей
    path('<int:post_id>/', NewsDetailView.as_view(), name='post_detail'), # Подробности поста
    path('search/', search_posts, name='search'), # Поиск
    path('create/', PostCreate.as_view(), name='post_create') # Создание постов
]

News_Portal/News_Portal/news/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse

class Author(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    rating = models.FloatField(default=0)

    def upgrade_rating(self):
        post_ratings = sum(post.rating * 3 for post in self.post_set.all())
        comment_ratings = sum(comment.rating for comment in Comment.objects.filter(user=self.user))
        author_comment_ratings = sum(comment.rating for post in self.post_set.all() for comment in Comment.objects.filter(post=post))
        self.rating = post_ratings + comment_ratings + author_comment_ratings
        self.save()

    def __str__(self):
        return self.user.username

class Category(models.Model):
    name = models.CharField(max_length=100, unique=True)

    def __str__(self):
        return self.name
    
class Post(models.Model):
    ARTICLE = 'AR'
    NEWS = 'NW'
    
    POST_TYPE_CHOICES = [
        (ARTICLE, 'Статья'),
        (NEWS, 'Новость'),
    ]

    author = models.ForeignKey(Author, on_delete=models.CASCADE)
    post_type = models.CharField(max_length=2, choices=POST_TYPE_CHOICES)
    created_at = models.DateTimeField(auto_now_add=True)
    categories = models.ManyToManyField(Category, through='PostCategory')
    title = models.CharField(max_length=200)
    content = models.TextField()
    rating = models.FloatField(default=0)

    def preview(self):
        return self.content[:124] + '...' if len(self.content) > 124 else self.content

    def like(self):
        self.rating += 1
        self.save()

    def dislike(self):
        self.rating -= 1
        self.save()

    def __str__(self):
        return self.title
    
    def get_absolute_url(self):
        return reverse("news:post_detail", args=[str(self.id)])
    
    
class PostCategory(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)

    class Meta:
        unique_together = ['post', 'category']

class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    text = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    rating = models.FloatField(default=0)

    def like(self):
        self.rating += 1
        self.save()

    def dislike(self):
        self.rating -= 1
        self.save()

    def __str__(self):
        return f'Comment by {self.user.username} on {self.post.title}'

class BadWord(models.Model):
    word = models.CharField(max_length=255)

    def __str__(self):
        return self.word

News_Portal/News_Portal/news/forms.py
from django import forms
from .models import Post
from django.core.exceptions import ValidationError

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = [
            'author',
            'post_type',
            'categories',
            'title',
            'content',
        ]

    def clean(self):
        cleaned_data = super().clean()
        content = cleaned_data.get('content')
        if content is not None and len(content) < 20:
            raise ValidationError({
                'content': "Описание не может содержат менее 20 символов"
            })
        
        name = cleaned_data.get('title')
        if name == content:
            raise ValidationError(
                "Описание не может быть идентично названию"
            )
        if name[0].islower():
            raise ValidationError(
                "Название должно быть с заглавной буквы"
            )
        return cleaned_data

News_Portal/News_Portal/news/views.py
from django.shortcuts import get_object_or_404
from django.views.generic import ListView, DetailView, CreateView, UpdateView
from .models import Post
from django.utils import timezone
from .filters import PostFilter
from django.shortcuts import render
from .forms import PostForm

class NewsListView(ListView):
    model = Post
    template_name = 'news/news_list.html' # Путь к шаблону
    context_object_name = 'posts' # Имя переменной которая будет использоваться в шаблоне 
    ordering = ['-created_at'] # Сортировка от новых к старым
    paginate_by = 10 # Укажите кол-во постов на 1 странице

    #def get_queryset(self): # Фильтр только новости
    #    return Post.objects.filter(post_type ='Новость')
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['post_count'] = self.get_queryset().count # Кол-во постов
        context['year'] = timezone.now().year # Текущий год
        return context

class NewsDetailView(DetailView):
    model = Post
    template_name = 'news/post_detail.html'
    context_object_name = 'post'

    def get_object(self):
        post = get_object_or_404(Post, id=self.kwargs['post_id'])
    #    if post.post_type != 'Новость':
    #       raise Http404('Новость не найдена.')
        return post
    
    # представление для поиска
def search_posts(request):
    f = PostFilter(request.GET, queryset=Post.objects.all())
    return render(request, 'news/search_result.html', {'filter': f})

class PostCreate(CreateView):
    form_class = PostForm
    model = Post
    template_name = 'news/post_edit.html'

class UpdateView(UpdateView):
    pass

News_Portal/News_Portal/news/templates/default.html
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Мой сайт{% endblock %}</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'news/css/styles.css' %}">  <!-- Подключение стилей -->
</head>
<body>
    <header>
        <h1>Мой веб-сайт</h1>
        <nav>
            <ul>
                {% block nav_links %}
                <li><a href="{% url 'news:news_list' %}">Главная страница</a></li>
                <!-- Другие ссылки -->
                 {% endblock %}
            </ul>
            <ul>
                <form method="get">
                    <input type="text" name="q" placeholder="Поиск постов..." required>
                    <button type="submit">Поиск</button>
                </form>
            </ul>
        </nav>
    </header>
    
    <main>
        {% block content %}
        {% endblock %}
    </main>

    <footer>
        <p>© {{ year }} Мой веб-сайт</p>
    </footer>
</body>
</html>

News_Portal/News_Portal/news/templates/news/news_list.html
{% extends "default.html" %}
{% load custom_filter %}

{% block title %}Новости{% endblock %}
{% block nav_links %}

{% endblock %}

{% block content %}
    <h2>Новости</h2>
    </p>Всего новостей: {{post_count }}</p>
    
    <form action="{% url 'news:search' %}" method="get">
        <input type="text" name="title" placeholder="Поиск по названию...">
        <input type="text" name="author" placeholder="Поиск по автору...">
        <input type="date" name="created_at">
        <button type="submit">Поиск</button>
    </form>

    <a href="{% url 'news:post_create' %}">Добавить новость</a>
    
    {% for post in posts %}
        <article>
            <h3><a href="{% url 'news:post_detail' post.id %}">{{ post.title|censor }}</a></h3>  <!-- Ссылка на детальную страницу поста -->
            <p><strong>Дата публикации:</strong> {{ post.created_at|date:"d.m.Y" }}</p>  <!-- Дата -->
            <p>{{ post.preview|truncatewords:20|censor }}...</p>  <!-- Первые 20 символов содержимого или 30 символов-->
            {% if post.content|length > 30 %}
                <p><a href="{% url 'news:post_detail' post.id %}">Читать далее</a></p>  
            {% endif %} 
        </article>
    {% empty %}
        <p>Нет новостей.</p>
    {% endfor %}
    <ul>
    {# Добавляем прогинацию на страницу #}
    {# Информация о предыдущей странице #}
    {% if page_obj.has_previous %}
        <a href='?page=1' >1</a>
        {% if page_obj.has_previous_page_number != 1%}
            ...
            <a href="?page={{ page_obj.has_previous_page_number }}"> {{ page_obj.has_previous_page_number}} </a>
        {%  endif %}
    {% endif %}
    {# Информация о текущей странице #}
    {{ page_obj.number }}
    {#Информация о текущей следующей странице #}
    {% if page_obj.has_next %}
    <a href="?page={{ page_obj.next_page_number }}">{{ page_obj.next_page_number }}</a>
    {% if paginator.num_pages != page_obj.next_page_number %}
        ...
        <a href="?page={{ page_obj.paginator.num_pages }}">{{ page_obj.paginator.num_pages }}</a>
    {% endif %}
{% endif %}
{% endblock content%}

News_Portal/News_Portal/news/templates/news/post_detail.html
{% extends "default.html" %}
{% load custom_filter %}

{% block title %}{{ post.title|censor }}{% endblock %}

{% block content %}
    <article>
        <h2>{{ post.title|censor }}</h2>
        <p><strong>Опубликовано:</strong> {{ post.created_at|date:"d.M.Y" }}</p>
        <p>{{ post.content|censor }}</p>
    </article>
    <a href="{% url 'news:news_list' %}">Назад к новостям</a>
{% endblock %}

News_Portal/News_Portal/news/templates/news/post_edit.html
{% extends 'default.html' %}

{% block content %}
<h1>Новость</h1>
<hr>
<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save" />
</form>
{% endblock %}

News_Portal/News_Portal/news/templates/news/search_result.html
{% extends 'default.html' %}

{% block content %}
    <h1>Результаты поиска</h1>
    <form action="{% url 'news:search' %}" method="get">
        <input type="text" name="title" placeholder="Поиск по названию...">
        <input type="text" name="author" placeholder="Поиск по автору...">
        <input type="date" name="created_at" placeholder="Дата публикации...">
        <button type="submit">Поиск</button>
    </form>
    <h2>Результаты поиска</h2>
    <ul>
        {% for post in filter.qs %}
            <li>{{ post.title }} - {{ post.author.username }} ({{ post.created_at }})</li>
        {% empty %}
            <li>Нет результатов.</li>
        {% endfor %}
    </ul>
{% endblock %}